### ISSUE TITLE
Suggestion: Auto-scaling for Nameplates

### ISSUE THREAD

**Issue by LorduFreeman** [earlSt1/vtt-custom-nameplates#3]
Liking this module a lot, the only thing I'm currently missing (apart from Custom Fonts):
Add auto-scaling of names depending on the zoom-level of the viewer (zooming out = names size up and vice versa).

**Comment by earlSt1** [comment]
Thanks, I like that idea! Might have a look into that at the weekend :)

**Comment by earlSt1** [comment]
Hi, I've started work on some kind of auto-scaling feature, it seems to work ok. If you'd like to test it you can install the testing version using this manifest: https://raw.githubusercontent.com/earlSt1/vtt-custom-nameplates/08x-update/test/module.json

In the font settings config window there is now an option for Auto scale (i dont think it's set to whatever the setting currently is, so it will always be unticked even if the setting is set).

**Comment by LorduFreeman** [comment]
Works pretty well for me (at far zoom levels it seems to stop scaling), thanks for including it!

**Comment by LorduFreeman** [comment]
Reopening issue for a bug report: Dragging a token and zooming while dragging causes a weird glitch where the token sticks to the relative position and stops getting dragged along.

**Comment by earlSt1** [comment]
Whoa thats so trippy :smile: I'll jump on it.

Also I pinched 2 lines from Kandashi's Easy Ruler Scale (https://github.com/kandashi/easy-ruler-scale)  so scaling will be a lot more pronounced when zooming out far

**Comment by earlSt1** [comment]
Feature now in v2.0.4
