### ISSUE TITLE
V10 Compatibility

### ISSUE THREAD

**Issue by XtraButtery** [earlSt1/vtt-custom-nameplates#6]
Custom Nameplates is no longer compatible with Foundry VTT V10.

I believe the reason is that it uses the outdated "token.hud" in its code, which was replaced as part of the migration to v10.

I'm not a coder, so I wasn't able to resolve this issue through my own investigation and a simple change of "token.hud" to the new "token.effects" didn't seem to work, however I do believe this is likely to be a minor fix of updating the API calls to whatever the most recent ones actually are.

**Comment by earlSt1** [comment]
Thanks for reminding me, finally figured out what needed to change (i did try when v10 was in testing but it was doing my head in). Just updating the module on foundry but then it should recognise the v10 version (v2.1.1)
