### ISSUE TITLE
[BUG] Autoscale not working with localStyle

### ISSUE THREAD

**Issue by kagedansa** [earlSt1/vtt-custom-nameplates#8]
The error occurs because the check for the local autoScale-variable is always "undefined".

To fix this, the if-query in line 101 must be changed.

from:

`    if ((localStyle[game.scenes.viewed.id] != null && localStyle.autoScale)`

to

`    if ((localStyle[game.scenes.viewed.id] != null && localStyle[game.scenes.viewed.id].autoScale)`

**Comment by earlSt1** [comment]
Hi, thanks for the report, sorry it's taken a while for me to respond. I'm gonna be doing a bunch of work on this module soon so will include this change with that update

**Comment by earlSt1** [comment]
Hi, sorry its 2 years late, been on a long break from foundry dev. Version 2.1.5 onwards should fix this issue. Feel free to open a new issue if it crops up again.
